---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: webapp1
spec:
 replicas: 2
 selector:
  matchLabels:
   app: webapp1
 template:
  metadata: 
   labels:
    app: webapp1
  spec:
   containers:
   - name: webapp1
     image: gcr.io/wired-climate-262921/mywebappgcr:tag
     ports:
     - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: mywebappgcr
spec:
  type: LoadBalancer
  selector:
    app: mywebappgcr
  ports:
    - protocol: TCP
      port: 6767
      targetPort: 8080
